heper_vm_ip: 192.168.0.170
bootstrap_ignition_url: "http://{{helper_vm_ip}}:8080/ignition/bootstrap.ign"  
config:
  provider: vsphere
  base_domain: pokitoach.com
  cluster_name: ocp4
  fips: false
  installer_ssh_key: "{{ lookup('file', '~/.ssh/ocp4.pub') }}"
  pull_secret: {}
vcenter:
  ip: 192.168.0.102
  datastore: VMs
  network: VM Network
  service_account_username: vault_vc_user
  service_account_password: vault_vc_pass
  admin_username: vault_vc_user 
  admin_password: vault_vc_pass
  datacenter: Datacenter
  folder_absolute_path:
  vm_power_state: poweredon
  template_name: rhcos-vmware
download:
  clients_url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest
  dependencies_url: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/latest/latest
  govc: https://github.com/vmware/govmomi/releases/download/v0.22.1/govc_linux_amd64.gz
bootstrap_vms: 
  - { name: "bootstrap", macaddr: "00:50:56:9B:24:F3", ipaddr: "192.168.0.171"}
master_vms:
  - { name: "master0", macaddr: "00:50:56:9B:FE:30", ipaddr: "192.168.0.172"}
  - { name: "master1", macaddr: "00:50:56:9B:E8:E0", ipaddr: "192.168.0.173"}
  - { name: "master2", macaddr: "00:50:56:9B:BE:5F", ipaddr: "192.168.0.174"}
worker_vms:      
  - { name: "worker0", macaddr: "00:50:56:9B:22:9C", ipaddr: "192.168.0.175"}
  - { name: "worker1", macaddr: "00:50:56:9B:66:69", ipaddr: "192.168.0.176"}
  - { name: "worker2", macaddr: "00:50:56:9b:0e:75", ipaddr: "192.168.0.177"}
static_ip:
  gateway: 192.168.0.1
  netmask: 255.255.255.0
  dns: "{{ helper_vm_ip }}"
  network_interface_name: ens192
proxy:
  enabled: false
  http_proxy: http://helper.ocp4.example.com:3129
  https_proxy: http://helper.ocp4.example.com:3129
  no_proxy: example.com
  cert_content: |
    -----BEGIN CERTIFICATE-----
        <certficate content>
    -----END CERTIFICATE-----  
registry:
  enabled: false
  product_repo: openshift-release-dev
  product_release_name: ocp-release
  product_release_version: 4.4.0-x86_64
  username: ansible
  password: ansible
  email: user@awesome.org
  cert_content:
  host: registry.ocp4.example.com
  port: 5000
  repo: ocp4/openshift4
ntp:
  custom: false
  ntp_server_list:
    - 0.rhel.pool.ntp.org
    - 1.rhel.pool.ntp.org
