apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  namespace: openshift-logging
  name: instance
spec:
  collection:
    logs:
      fluentd:
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 1Gi 
      type: fluentd
  curation:
    curator:
      schedule: 0 12 * * *
    type: curator
  logStore:
    elasticsearch:
      nodeCount: 3
      redundancyPolicy: SingleRedundancy
      resources:
        limits:
          memory: 12Gi
        requests:
          cpu: "1"
          memory: 12Gi
      storage:
        size: 20Gi
        storageClassName: csi-sc
    retentionPolicy:
      application:
        maxAge: 7d
      audit:
        maxAge: 7d
      infra:
        maxAge: 1d
    type: elasticsearch
  managementState: Managed
  visualization:
    kibana:
      replicas: 1
    type: kibana
