kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: csi-regpvc
  annotations:
    volume.beta.kubernetes.io/storage-class: csi-sc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
